version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/archive-processor"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/runners/at-austrocontrol-registry"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/runners/au-casa-registry"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/runners/bg-caa-registry"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/runners/br-anac-registry"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/runners/bs-caa-registry"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/runners/bz-bdca-registry"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/runners/ca-transport-canada-registry"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/runners/ch-bazl-registry"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/runners/cy-dca-registry"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/runners/cz-caa-registry"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/runners/ee-transpordiamet-registry"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/runners/es-aesa-registry"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/runners/fr-dgac-registry"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/runners/ge-gcaa-registry"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/runners/gg-2reg-registry"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/runners/hr-ccaa-registry"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/runners/hu-kozhaf-registry"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/runners/im-ardis-registry"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/runners/is-samgongustofa-registry"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/runners/kg-caa-registry"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/runners/kr-koca-registry"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/runners/ky-caa-registry"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/runners/lu-dac-registry"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/runners/lv-caa-registry"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/runners/md-caa-registry"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/runners/me-caa-registry"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/runners/mictronics"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/runners/mk-caa-registry"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/runners/mv-caa-registry"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/runners/nl-ilt-registry"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/runners/no-caa-registry"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/runners/nz-caa-registry"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/runners/ourairports"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/runners/pg-casapng-registry"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/runners/rs-cad-registry"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/runners/sg-caas-registry"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/runners/sk-nsat-registry"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/runners/tc-caa-registry"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/runners/uk-caa-registry"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/runners/us-faa-registry"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/message-processor"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/receiver"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/shared"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/tools/traffic-recorder"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/tools/traffic-replayer"
    schedule:
      interval: "weekly"
