services:

  receiver:
    image: ghcr.io/brentio/skyfollower-receiver:latest
    restart: unless-stopped
    volumes:
      - ./config/receiver/settings.json:/app/settings.json:ro
      - receiver-queue:/app/data

volumes:
  receiver-queue:
