services:

  archive-processor:
    image: ghcr.io/brentio/skyfollower-archive:latest
    restart: unless-stopped
    volumes:
      - ./config/archive/settings.json:/app/settings.json:ro
      - archive-data:/app/data
    networks:
      - skyfollower

  ui:
    image: ghcr.io/brentio/skyfollower-ui:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./config/ui/settings.json:/app/settings.json:ro
    networks:
      - skyfollower

volumes:
  archive-data:

networks:
  skyfollower:
    driver: bridge
