@startuml
!include_once ../../images/common-component.iuml

!startsub COMPONENT
package "Central Server" as CentralSvr $OnPrem {
    package "RabbitMQ" as Rabbit {
        entity "adsb\n(x-consistent-hash)" as adsbx
        queue "adsb-{MESSAGE_PROCESSOR_ID}" as adsbq
        queue "archive" as archiveq

        adsbx -down-> adsbq : Routing key icao_hex,\nbinding weight 1
    }
    database "Redis" as Redis
}
!endsub

@enduml
