!include common.iuml

skinparam defaultTextAlignment center
skinparam component {
    BorderColor black
    BackgroundColor white
}
skinparam package {
    BorderColor black
    BackgroundColor white
    FontStyle bold
}

!$AWS = "#ffdbbb"
!$OnPrem = "#a8e5fa"
!$Vendor = "#d989c9"

legend bottom
**Color Legend**
|<back:$OnPrem>      | On-Premises |
|<back:$AWS>      | AWS |
|<back:$Vendor>      | Third-Party Vendor |
endlegend
